//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NebulaSkin.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class cs_CZ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal cs_CZ() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NebulaSkin.Resources.cs_CZ", typeof(cs_CZ).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Created by goldfinsh과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_By {
            get {
                return ResourceManager.GetString("Label_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Champion : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Cham_Name {
            get {
                return ResourceManager.GetString("Label_Cham_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chromas과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Chor_Name {
            get {
                return ResourceManager.GetString("Label_Chor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Howling Abyss과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Map_HA {
            get {
                return ResourceManager.GetString("Label_Map_HA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Summoner&apos;s Rift과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Map_SRU {
            get {
                return ResourceManager.GetString("Label_Map_SRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Twisted Treeline과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Map_TT {
            get {
                return ResourceManager.GetString("Label_Map_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minions : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Minions {
            get {
                return ResourceManager.GetString("Label_Minions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Classic Minions과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Minions_0 {
            get {
                return ResourceManager.GetString("Label_Minions_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pool Party Minions과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Minions_1 {
            get {
                return ResourceManager.GetString("Label_Minions_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Project Minions과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Minions_2 {
            get {
                return ResourceManager.GetString("Label_Minions_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skier Minions과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Minions_3 {
            get {
                return ResourceManager.GetString("Label_Minions_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Draven Minions과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Minions_4 {
            get {
                return ResourceManager.GetString("Label_Minions_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Star Guardian Minions과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Minions_5 {
            get {
                return ResourceManager.GetString("Label_Minions_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thx : test, Definitely not kappa, stefsot, Hellsing, coman3과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_NoticeThx {
            get {
                return ResourceManager.GetString("Label_NoticeThx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Coming soon 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_NotYet {
            get {
                return ResourceManager.GetString("Label_NotYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skin과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Skin {
            get {
                return ResourceManager.GetString("Label_Skin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Team Color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_TeamColor {
            get {
                return ResourceManager.GetString("Label_TeamColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Up : Red  /  Down : Blue과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_TeamColor_0 {
            get {
                return ResourceManager.GetString("Label_TeamColor_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Up : Blue  /  Down : Red과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_TeamColor_1 {
            get {
                return ResourceManager.GetString("Label_TeamColor_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ward과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Ward {
            get {
                return ResourceManager.GetString("Label_Ward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Jazyk ( Language, 언어 )  /  Apply : F5과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Language_Select {
            get {
                return ResourceManager.GetString("Main_Language_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you like this addon, hope Upvote click or donation. 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Text_1 {
            get {
                return ResourceManager.GetString("Main_Text_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Donated amount will be used for the development of better addon. Thank you.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Text_2 {
            get {
                return ResourceManager.GetString("Main_Text_2", resourceCulture);
            }
        }
    }
}
