//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NebulaSkin.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ko_KR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ko_KR() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NebulaSkin.Resources.ko_KR", typeof(ko_KR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   챔피언 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Lable_Cham_Name {
            get {
                return ResourceManager.GetString("Lable_Cham_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   크로마과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Lable_Chor_Name {
            get {
                return ResourceManager.GetString("Lable_Chor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   와드 자동 변경과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Lable_Ward_Auto {
            get {
                return ResourceManager.GetString("Lable_Ward_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   와드과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Lable_Ward_Error_0 {
            get {
                return ResourceManager.GetString("Lable_Ward_Error_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   자동 변경 옵션은 크래쉬 방지를 위해 약 2초뒤에 적용되지만. 때때로 크래쉬가 일어납니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Lable_Ward_Error_1 {
            get {
                return ResourceManager.GetString("Lable_Ward_Error_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스킨이 완벽하게 적용된 후, 다음 스킨값을 바꿔주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Lable_Ward_Error_2 {
            get {
                return ResourceManager.GetString("Lable_Ward_Error_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   와드과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Lable_Ward_Skin {
            get {
                return ResourceManager.GetString("Lable_Ward_Skin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   언어 선택 후 F5를 눌러 적용합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Language_Exp {
            get {
                return ResourceManager.GetString("Main_Language_Exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   언어 ( Language )과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Language_Select {
            get {
                return ResourceManager.GetString("Main_Language_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스킨과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Skin {
            get {
                return ResourceManager.GetString("Main_Skin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ Nebula ] Skin - 6.19.0.2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Text_0 {
            get {
                return ResourceManager.GetString("Main_Text_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이 애드온이 마음에 드신다면, 추천 또는 기부 부탁드립니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Text_1 {
            get {
                return ResourceManager.GetString("Main_Text_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기부하신 금액은 더 나은 애드온 개발과 치킨을 위해 사용됩니다. 감사합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Text_2 {
            get {
                return ResourceManager.GetString("Main_Text_2", resourceCulture);
            }
        }
    }
}
