//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NebulaTeemo.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang_Kor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang_Kor() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NebulaTeemo.Resources.Lang_Kor", typeof(Lang_Kor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   티모 사거리 - [ 평타 : 500 ] [ Q : 680 ] [ R : 400 / 650 / 900 ]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Attack_Range_Exp {
            get {
                return ResourceManager.GetString("Attack_Range_Exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ 점화 ] 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Combo_Ignite {
            get {
                return ResourceManager.GetString("Combo_Ignite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   보유 마나가 [ n% ] 이상일 때 [ Q ]을 사용합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Combo_Q_Mana {
            get {
                return ResourceManager.GetString("Combo_Q_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ Q ] 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Combo_Q_Text {
            get {
                return ResourceManager.GetString("Combo_Q_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   보유한 [ 버섯 ] 개수가 [ n ]개 보다 많으면 [ R ]을 사용합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Combo_R_Count {
            get {
                return ResourceManager.GetString("Combo_R_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ R ] 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Combo_R_Text {
            get {
                return ResourceManager.GetString("Combo_R_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   보유 마나가 [ n% ] 이상일 때 [ W ]를 사용합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Combo_W_Mana {
            get {
                return ResourceManager.GetString("Combo_W_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   적이 [ n ] ~ [ 800 ]사이에 있으면 [ W ]를 사용합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Combo_W_Range {
            get {
                return ResourceManager.GetString("Combo_W_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ W ] 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Combo_W_Text {
            get {
                return ResourceManager.GetString("Combo_W_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   적 스펠 범위과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Draw_Enemy {
            get {
                return ResourceManager.GetString("Draw_Enemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ Q ] 범위 - [ 시즈 미니언 킬 ]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Draw_LaneQ {
            get {
                return ResourceManager.GetString("Draw_LaneQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ Q ] 범위과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Draw_Q {
            get {
                return ResourceManager.GetString("Draw_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ R ] 범위과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Draw_R {
            get {
                return ResourceManager.GetString("Draw_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   범위 확인 - 거리를 확인하고 싶을 때 사용합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Draw_Virtual {
            get {
                return ResourceManager.GetString("Draw_Virtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   범위 2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Draw_Virtual_Max {
            get {
                return ResourceManager.GetString("Draw_Virtual_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   범위 1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Draw_Virtual_Min {
            get {
                return ResourceManager.GetString("Draw_Virtual_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   적이 [ n ]범위 안에 있으면 [ Q ]을 사용합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Flee_Q_Range {
            get {
                return ResourceManager.GetString("Flee_Q_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ Q ] 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Flee_Q_Text {
            get {
                return ResourceManager.GetString("Flee_Q_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ R ] 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Flee_R_Text {
            get {
                return ResourceManager.GetString("Flee_R_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ W ] 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Flee_W_Text {
            get {
                return ResourceManager.GetString("Flee_W_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   보유 마나가 [ n% ] 이상일 때 [ Q ]를 사용합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Harass_Q_Mana {
            get {
                return ResourceManager.GetString("Harass_Q_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   적이 [ n ]범위 안에 있으면 [ Q ]을 사용합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Harass_Q_Range {
            get {
                return ResourceManager.GetString("Harass_Q_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ Q ] 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Harass_Q_Text {
            get {
                return ResourceManager.GetString("Harass_Q_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   보유한 [ 버섯 ] 개수가 [ n ]개 보다 많으면 [ R ]을 사용합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Harass_R_Count {
            get {
                return ResourceManager.GetString("Harass_R_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   보유 마나가 [ n% ] 이상일 때 [ R ]을 사용합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Harass_R_Mana {
            get {
                return ResourceManager.GetString("Harass_R_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ R ] 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Harass_R_Text {
            get {
                return ResourceManager.GetString("Harass_R_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서포트 모드과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Harass_SuppotMode {
            get {
                return ResourceManager.GetString("Harass_SuppotMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   보유 마나가 [ n% ] 이상일 때 [ W ]를 사용합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Harass_W_Mana {
            get {
                return ResourceManager.GetString("Harass_W_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   적이 [ n ] ~ [ 800 ]사이에 있으면 [ W ]를 사용합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Harass_W_Range {
            get {
                return ResourceManager.GetString("Harass_W_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ W ] 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Harass_W_Text {
            get {
                return ResourceManager.GetString("Harass_W_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   몰락한 왕의 검과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_A_BK {
            get {
                return ResourceManager.GetString("Item_A_BK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용자의 체력이 [ n% ] 이하일 때 [ 몰락한 왕의 검 ] 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_A_BK_Hp {
            get {
                return ResourceManager.GetString("Item_A_BK_Hp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   빌지워터 해적검과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_A_BW {
            get {
                return ResourceManager.GetString("Item_A_BW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   마법공학 총검과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_A_Hex {
            get {
                return ResourceManager.GetString("Item_A_Hex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   요우무의 유령검과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_A_Youmuu {
            get {
                return ResourceManager.GetString("Item_A_Youmuu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   실명과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_Buff_Blind {
            get {
                return ResourceManager.GetString("Item_Buff_Blind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   매혹과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_Buff_Charm {
            get {
                return ResourceManager.GetString("Item_Buff_Charm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   공포과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_Buff_Fear {
            get {
                return ResourceManager.GetString("Item_Buff_Fear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변형과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_Buff_Ploymorph {
            get {
                return ResourceManager.GetString("Item_Buff_Ploymorph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   독과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_Buff_Poisons {
            get {
                return ResourceManager.GetString("Item_Buff_Poisons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   침묵과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_Buff_Silence {
            get {
                return ResourceManager.GetString("Item_Buff_Silence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   느려짐과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_Buff_Slow {
            get {
                return ResourceManager.GetString("Item_Buff_Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   속박과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_Buff_Snare {
            get {
                return ResourceManager.GetString("Item_Buff_Snare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기절과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_Buff_Stun {
            get {
                return ResourceManager.GetString("Item_Buff_Stun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   제압과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_Buff_Supression {
            get {
                return ResourceManager.GetString("Item_Buff_Supression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   도발과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_Buff_Taunt {
            get {
                return ResourceManager.GetString("Item_Buff_Taunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ 수은장식띠 / 헤르메스의 시미터 ]의 시전 속도 - [ /ms ]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_CastDelay {
            get {
                return ResourceManager.GetString("Item_CastDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수은장식띠과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_D_QSS {
            get {
                return ResourceManager.GetString("Item_D_QSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   헤르메스의 시미터과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_D_Scimitar {
            get {
                return ResourceManager.GetString("Item_D_Scimitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   순간 데미지가 [ n% ] 이상 들어오면  [ 존야의 모래시계 ]를 사용합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_D_Zhonyas_Dmg {
            get {
                return ResourceManager.GetString("Item_D_Zhonyas_Dmg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용자의 체력이 [ n% ] 이하일 때 [ 존야의 모래시계 ] 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_D_Zhonyas_Hp {
            get {
                return ResourceManager.GetString("Item_D_Zhonyas_Hp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   위험한 궁극기[ R ]를 선택하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_D_Zhonyas_R {
            get {
                return ResourceManager.GetString("Item_D_Zhonyas_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   존야의 모래시계과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_D_Zhonyas_Text {
            get {
                return ResourceManager.GetString("Item_D_Zhonyas_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ 수은 장식띠, 헤르메스의 시미터 ]로 해제할 효과과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_Debuff_Text {
            get {
                return ResourceManager.GetString("Item_Debuff_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※ 콤보모드에서만 작동합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_Exp_0 {
            get {
                return ResourceManager.GetString("Item_Exp_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※ 항상 작동합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_Exp_1 {
            get {
                return ResourceManager.GetString("Item_Exp_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   메뉴 [ x ] 사용 [ o ] - [ 빌지워터 해적검 ] [ 요우무의 유령검 ] [ 마법공학 총검 ]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_Item_Text {
            get {
                return ResourceManager.GetString("Item_Item_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   점화과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_S_Ignite {
            get {
                return ResourceManager.GetString("Item_S_Ignite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   보유 마나가 [ n% ] 이상일 때 [ Q ]를 사용합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Jungle_Q_Mana {
            get {
                return ResourceManager.GetString("Jungle_Q_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ Q ] 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Jungle_Q_Text {
            get {
                return ResourceManager.GetString("Jungle_Q_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   보유한 [ 버섯 ] 개수가 [ n ]개 보다 많으면 [ R ]을 사용합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Jungle_R_Count {
            get {
                return ResourceManager.GetString("Jungle_R_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   보유 마나가 [ n% ] 이상일 때 [ R ]을 사용합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Jungle_R_Mana {
            get {
                return ResourceManager.GetString("Jungle_R_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ R ] 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Jungle_R_Text {
            get {
                return ResourceManager.GetString("Jungle_R_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ Q ] 사용 - 대포 미니언과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Lane_Q_Big {
            get {
                return ResourceManager.GetString("Lane_Q_Big", resourceCulture);
            }
        }
        
        /// <summary>
        ///   보유한 [ 버섯 ] 개수가 [ n ]개 보다 많으면 [ R ]을 사용합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Lane_R_Count {
            get {
                return ResourceManager.GetString("Lane_R_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   보유 마나가 [ n% ] 이상일 때 [ R ]을 사용합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Lane_R_Mana {
            get {
                return ResourceManager.GetString("Lane_R_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ R ]을 사용하여 중독시킬 미니언의 개수과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Lane_R_PoisonCount {
            get {
                return ResourceManager.GetString("Lane_R_PoisonCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ R ] 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Lane_R_Text {
            get {
                return ResourceManager.GetString("Lane_R_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   언어 선택 후 F5를 눌러 적용합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Language_Exp {
            get {
                return ResourceManager.GetString("Main_Language_Exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   언어 ( Language )과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Language_Select {
            get {
                return ResourceManager.GetString("Main_Language_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ Nebula ] Teemo - 6.21.0.1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Text_0 {
            get {
                return ResourceManager.GetString("Main_Text_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이 애드온이 마음에 드신다면, 추천 또는 기부 부탁드립니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Text_1 {
            get {
                return ResourceManager.GetString("Main_Text_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기부하신 금액은 더 나은 애드온 개발을 위해 사용됩니다. 감사합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Text_2 {
            get {
                return ResourceManager.GetString("Main_Text_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   자동 [ R ] 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_AutoR {
            get {
                return ResourceManager.GetString("Misc_AutoR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   적 챔피언이 [ 존야 / 귀환 / 에어본 / 스턴 / 속박 ] 상태일 때 [ R ]을 사용합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_AutoR_Exp {
            get {
                return ResourceManager.GetString("Misc_AutoR_Exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   자동 [ R ]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_AutoR_Text {
            get {
                return ResourceManager.GetString("Misc_AutoR_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정글 스틸 - [ 에픽 몬스터 ]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_JungleSteal {
            get {
                return ResourceManager.GetString("Misc_JungleSteal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ Q ]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_JungleSteal_0 {
            get {
                return ResourceManager.GetString("Misc_JungleSteal_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ Q ] + [ E ]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_JungleSteal_1 {
            get {
                return ResourceManager.GetString("Misc_JungleSteal_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   킬 스틸과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_KillSteal {
            get {
                return ResourceManager.GetString("Misc_KillSteal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ 점화 ]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_KillSteal_0 {
            get {
                return ResourceManager.GetString("Misc_KillSteal_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ 점화 ] + [ Q ]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_KillSteal_1 {
            get {
                return ResourceManager.GetString("Misc_KillSteal_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ 점화 ] + [ Q ] + [ 총검 ]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_KillSteal_2 {
            get {
                return ResourceManager.GetString("Misc_KillSteal_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ Q ]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_KillSteal_3 {
            get {
                return ResourceManager.GetString("Misc_KillSteal_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ Q ] + [ E ]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_KillSteal_4 {
            get {
                return ResourceManager.GetString("Misc_KillSteal_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ Q ] + [ E ] + [ 총검 ]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_KillSteal_5 {
            get {
                return ResourceManager.GetString("Misc_KillSteal_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ E ]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_KillSteal_6 {
            get {
                return ResourceManager.GetString("Misc_KillSteal_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ E ] + [ 총검 ]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_KillSteal_7 {
            get {
                return ResourceManager.GetString("Misc_KillSteal_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   킬 스틸과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_KillSteal_Text {
            get {
                return ResourceManager.GetString("Misc_KillSteal_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   클래식 티모과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_Skin_Id_0 {
            get {
                return ResourceManager.GetString("Misc_Skin_Id_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   행복한 엘프 티모과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_Skin_Id_1 {
            get {
                return ResourceManager.GetString("Misc_Skin_Id_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정찰부대 티모과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_Skin_Id_2 {
            get {
                return ResourceManager.GetString("Misc_Skin_Id_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   오소리 티모과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_Skin_Id_3 {
            get {
                return ResourceManager.GetString("Misc_Skin_Id_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   우주비행사 티모과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_Skin_Id_4 {
            get {
                return ResourceManager.GetString("Misc_Skin_Id_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   복실복실 티모과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_Skin_Id_5 {
            get {
                return ResourceManager.GetString("Misc_Skin_Id_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   슈퍼 티모과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_Skin_Id_6 {
            get {
                return ResourceManager.GetString("Misc_Skin_Id_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   판다 티모과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_Skin_Id_7 {
            get {
                return ResourceManager.GetString("Misc_Skin_Id_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   오메가 분대 티모과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_Skin_Id_8 {
            get {
                return ResourceManager.GetString("Misc_Skin_Id_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스킨과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_Skin_Select {
            get {
                return ResourceManager.GetString("Misc_Skin_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스킨 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_Skin_Text {
            get {
                return ResourceManager.GetString("Misc_Skin_Text", resourceCulture);
            }
        }
    }
}
