//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NebulaKalista.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang_Kor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang_Kor() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NebulaKalista.Resources.Lang_Kor", typeof(Lang_Kor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   [ E ] 공격력을 [ 적 ] 체력바에 표시과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Draw_E_Dmg_Champ {
            get {
                return ResourceManager.GetString("Draw_E_Dmg_Champ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ E ] 공격력을 [ 몬스터 ] 체력바에 표시과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Draw_E_Dmg_Monster {
            get {
                return ResourceManager.GetString("Draw_E_Dmg_Monster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ E ] 공격력% 위치과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Draw_E_Percent_Str {
            get {
                return ResourceManager.GetString("Draw_E_Percent_Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용안함과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Draw_E_Percent0 {
            get {
                return ResourceManager.GetString("Draw_E_Percent0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   체력바 옆에과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Draw_E_Percent1 {
            get {
                return ResourceManager.GetString("Draw_E_Percent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   체력바 위에과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Draw_E_Percent2 {
            get {
                return ResourceManager.GetString("Draw_E_Percent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   챔피언 이름 위에과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Draw_E_Percent3 {
            get {
                return ResourceManager.GetString("Draw_E_Percent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사이드바과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Draw_E_Percent4 {
            get {
                return ResourceManager.GetString("Draw_E_Percent4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사이드바 [ X ] 위치과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Draw_E_Sidebar_X {
            get {
                return ResourceManager.GetString("Draw_E_Sidebar_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사이드바 [ Y ] 위치과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Draw_E_Sidebar_Y {
            get {
                return ResourceManager.GetString("Draw_E_Sidebar_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ E ] 범위과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Draw_Range_E {
            get {
                return ResourceManager.GetString("Draw_Range_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ Q ] 범위과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Draw_Range_Q {
            get {
                return ResourceManager.GetString("Draw_Range_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ R ] 범위과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Draw_Range_R {
            get {
                return ResourceManager.GetString("Draw_Range_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ E ] 사용 - [ 대형 + 미니 ]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Farm_Jungle_E_All {
            get {
                return ResourceManager.GetString("Farm_Jungle_E_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ E ] 사용 - [ 대형 ]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Farm_Jungle_E_Big {
            get {
                return ResourceManager.GetString("Farm_Jungle_E_Big", resourceCulture);
            }
        }
        
        /// <summary>
        ///   보유 마나가 [ n% ] 이상일 때 [ Q E ] 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Farm_Jungle_Mana {
            get {
                return ResourceManager.GetString("Farm_Jungle_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ Q ] 사용 - [ 대형 + 미니 ]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Farm_Jungle_Q_All {
            get {
                return ResourceManager.GetString("Farm_Jungle_Q_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ Q ] 사용 - [ 대형 ]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Farm_Jungle_Q_Big {
            get {
                return ResourceManager.GetString("Farm_Jungle_Q_Big", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정글 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Farm_Jungle_Str {
            get {
                return ResourceManager.GetString("Farm_Jungle_Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ E ] 사용 - [ 모든 미니언 ]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Farm_Lane_E_All {
            get {
                return ResourceManager.GetString("Farm_Lane_E_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ E ] 사용 - [ 대포, 슈퍼 미니언 ]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Farm_Lane_E_Big {
            get {
                return ResourceManager.GetString("Farm_Lane_E_Big", resourceCulture);
            }
        }
        
        /// <summary>
        ///   보유 마나가 [ n% ] 이상일 때 [ E ] 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Farm_Lane_E_Mana {
            get {
                return ResourceManager.GetString("Farm_Lane_E_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   미니언 킬 개수가 [ n ] 이상일 때 [ E ] 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Farm_Lane_E_Num {
            get {
                return ResourceManager.GetString("Farm_Lane_E_Num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ Q ] 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Farm_Lane_Q {
            get {
                return ResourceManager.GetString("Farm_Lane_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   보유 마나가 [ n% ] 이상일 때 [ Q ] 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Farm_Lane_Q_Mana {
            get {
                return ResourceManager.GetString("Farm_Lane_Q_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   미니언 킬 개수가 [ n ]보다 많을 때 [ Q ] 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Farm_Lane_Q_Num {
            get {
                return ResourceManager.GetString("Farm_Lane_Q_Num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   라인 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Farm_Lane_Str {
            get {
                return ResourceManager.GetString("Farm_Lane_Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   언어 ( Language )과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Intro_Language_Select {
            get {
                return ResourceManager.GetString("Intro_Language_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   언어 선택 후 F5를 눌러 적용합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Intro_Language_Str {
            get {
                return ResourceManager.GetString("Intro_Language_Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ Nebula ] Kalista - 6.16.0.0과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Intro_Str_0 {
            get {
                return ResourceManager.GetString("Intro_Str_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이 Addon이 마음에 든다면, 추천 또는 기부를 부탁드립니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Intro_Str_1 {
            get {
                return ResourceManager.GetString("Intro_Str_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   치킨을 먹을 수 있게 도와주세요...ㅠ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Intro_Str_2 {
            get {
                return ResourceManager.GetString("Intro_Str_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   몰락한 왕의 검과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_A_Blade {
            get {
                return ResourceManager.GetString("Item_A_Blade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용자의 체력이 [ n% ] 이하일 때 [ 몰락한 왕의 검 ] 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_A_Blade_Hp {
            get {
                return ResourceManager.GetString("Item_A_Blade_Hp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   빌지워터 해적검과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_A_Blige {
            get {
                return ResourceManager.GetString("Item_A_Blige", resourceCulture);
            }
        }
        
        /// <summary>
        ///   요우무의 유령검과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_A_Youmu {
            get {
                return ResourceManager.GetString("Item_A_Youmu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   실명과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_Buff_Blind {
            get {
                return ResourceManager.GetString("Item_Buff_Blind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   매혹과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_Buff_Charm {
            get {
                return ResourceManager.GetString("Item_Buff_Charm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   공포과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_Buff_Fear {
            get {
                return ResourceManager.GetString("Item_Buff_Fear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   에어본과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_Buff_Knockup {
            get {
                return ResourceManager.GetString("Item_Buff_Knockup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변형과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_Buff_Ploymorph {
            get {
                return ResourceManager.GetString("Item_Buff_Ploymorph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   독과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_Buff_Poisons {
            get {
                return ResourceManager.GetString("Item_Buff_Poisons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   침묵과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_Buff_Silence {
            get {
                return ResourceManager.GetString("Item_Buff_Silence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   느려짐과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_Buff_Slow {
            get {
                return ResourceManager.GetString("Item_Buff_Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기절과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_Buff_Stun {
            get {
                return ResourceManager.GetString("Item_Buff_Stun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   제압과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_Buff_Supression {
            get {
                return ResourceManager.GetString("Item_Buff_Supression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   도발과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_Buff_Taunt {
            get {
                return ResourceManager.GetString("Item_Buff_Taunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ 수은 장식띠, 헤르메스의 시미터 ]의 시전 속도 - [ /ms ]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_D_CastDelay {
            get {
                return ResourceManager.GetString("Item_D_CastDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   헤르메스의 시미터과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_D_Mercurial {
            get {
                return ResourceManager.GetString("Item_D_Mercurial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수은 장식띠과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_D_QuickSilver {
            get {
                return ResourceManager.GetString("Item_D_QuickSilver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ 수은 장식띠, 헤르메스의 시미터 ]로 해제할 효과과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_D_Str {
            get {
                return ResourceManager.GetString("Item_D_Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※ 콤보모드에서만 작동합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_Srt {
            get {
                return ResourceManager.GetString("Item_Srt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ E ] 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Combo_E {
            get {
                return ResourceManager.GetString("Main_Combo_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   보유 마나가 [ n% ] 이상일 때 [ E ] 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Combo_E_Mana {
            get {
                return ResourceManager.GetString("Main_Combo_E_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ Q ] 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Combo_Q {
            get {
                return ResourceManager.GetString("Main_Combo_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   보유 마나가 [ n% ] 이상일 때 [ Q ] 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Combo_Q_Mana {
            get {
                return ResourceManager.GetString("Main_Combo_Q_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   콤보 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Combo_Str {
            get {
                return ResourceManager.GetString("Main_Combo_Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ W ] 패시브 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Combo_W {
            get {
                return ResourceManager.GetString("Main_Combo_W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ Q ] 스타일과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Como_QStyle {
            get {
                return ResourceManager.GetString("Main_Como_QStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선 [ Q ]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Como_QStyle0 {
            get {
                return ResourceManager.GetString("Main_Como_QStyle0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   평 ⇒ [ Q ] ⇒ [ E ]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Como_QStyle1 {
            get {
                return ResourceManager.GetString("Main_Como_QStyle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ E ] 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Harass_E {
            get {
                return ResourceManager.GetString("Main_Harass_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   보유 마나가 [ n% ] 이상일 때 [ E ] 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Harass_E_Mana {
            get {
                return ResourceManager.GetString("Main_Harass_E_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ E ] 스택 개수 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Harass_E_Stack {
            get {
                return ResourceManager.GetString("Main_Harass_E_Stack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ Q ] 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Harass_Q {
            get {
                return ResourceManager.GetString("Main_Harass_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   보유 마나가 [ n% ] 이상일 때 [ Q ] 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Harass_Q_Mana {
            get {
                return ResourceManager.GetString("Main_Harass_Q_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   견제 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Harass_Str {
            get {
                return ResourceManager.GetString("Main_Harass_Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   죽기전에 [ E ] 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_E_Death {
            get {
                return ResourceManager.GetString("Misc_E_Death", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용자의 체력이 [ n% ] 이하일 때 [ E ] 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_E_Death_Hp {
            get {
                return ResourceManager.GetString("Misc_E_Death_Hp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ E ] 공격력 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_E_Dmg {
            get {
                return ResourceManager.GetString("Misc_E_Dmg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ E ] 공격력을 [ n ] 만큼 줄여서 계산과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_E_Dmg_Value {
            get {
                return ResourceManager.GetString("Misc_E_Dmg_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   킬 스틸과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_E_Steal_H {
            get {
                return ResourceManager.GetString("Misc_E_Steal_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정글 스틸과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_E_Steal_J {
            get {
                return ResourceManager.GetString("Misc_E_Steal_J", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ E ] 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_E_Str {
            get {
                return ResourceManager.GetString("Misc_E_Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   계약자 보호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_R_Save {
            get {
                return ResourceManager.GetString("Misc_R_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   계약자 체력이 [ n% ] 이하일 때 [ R ] 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_R_Save_Hp {
            get {
                return ResourceManager.GetString("Misc_R_Save_Hp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ R ] 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_R_Str {
            get {
                return ResourceManager.GetString("Misc_R_Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스킨 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_Skin {
            get {
                return ResourceManager.GetString("Misc_Skin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용안함과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_Skin_0 {
            get {
                return ResourceManager.GetString("Misc_Skin_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   불의 축체 칼리스타과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_Skin_1 {
            get {
                return ResourceManager.GetString("Misc_Skin_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   챔피언십 칼리스타과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_Skin_2 {
            get {
                return ResourceManager.GetString("Misc_Skin_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SKT T1 칼리스타과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_Skin_3 {
            get {
                return ResourceManager.GetString("Misc_Skin_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스킨과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_Skin_Text {
            get {
                return ResourceManager.GetString("Misc_Skin_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   벽점프 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_WallJump {
            get {
                return ResourceManager.GetString("Misc_WallJump", resourceCulture);
            }
        }
    }
}
