//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NebulaKalista.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang_En {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang_En() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NebulaKalista.Resources.Lang_En", typeof(Lang_En).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   [ E ] Damage Indicator - Enemy Hp bar과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Draw_E_Dmg_Champ {
            get {
                return ResourceManager.GetString("Draw_E_Dmg_Champ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ E ] Damage Indicator - Monster Hp bar과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Draw_E_Dmg_Monster {
            get {
                return ResourceManager.GetString("Draw_E_Dmg_Monster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ E ] Damage % position과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Draw_E_Percent_Str {
            get {
                return ResourceManager.GetString("Draw_E_Percent_Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Off과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Draw_E_Percent0 {
            get {
                return ResourceManager.GetString("Draw_E_Percent0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Near Hp bar과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Draw_E_Percent1 {
            get {
                return ResourceManager.GetString("Draw_E_Percent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   On the Hp bar과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Draw_E_Percent2 {
            get {
                return ResourceManager.GetString("Draw_E_Percent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   On the Hero name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Draw_E_Percent3 {
            get {
                return ResourceManager.GetString("Draw_E_Percent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sidebar과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Draw_E_Percent4 {
            get {
                return ResourceManager.GetString("Draw_E_Percent4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sidebar [ X ] position과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Draw_E_Sidebar_X {
            get {
                return ResourceManager.GetString("Draw_E_Sidebar_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sidebar [ Y ] position과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Draw_E_Sidebar_Y {
            get {
                return ResourceManager.GetString("Draw_E_Sidebar_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ E ] Range과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Draw_Range_E {
            get {
                return ResourceManager.GetString("Draw_Range_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ Q ] Range과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Draw_Range_Q {
            get {
                return ResourceManager.GetString("Draw_Range_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ R ] Range과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Draw_Range_R {
            get {
                return ResourceManager.GetString("Draw_Range_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ E ] Use - [ Big + Mini ]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Farm_Jungle_E_All {
            get {
                return ResourceManager.GetString("Farm_Jungle_E_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ E ] Use - [ Big ]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Farm_Jungle_E_Big {
            get {
                return ResourceManager.GetString("Farm_Jungle_E_Big", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If mana is higher than [ n% ], [ Q E ] is used 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Farm_Jungle_Mana {
            get {
                return ResourceManager.GetString("Farm_Jungle_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ Q ] Use - [ Big + Mini ]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Farm_Jungle_Q_All {
            get {
                return ResourceManager.GetString("Farm_Jungle_Q_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ Q ] Use - [ Big ]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Farm_Jungle_Q_Big {
            get {
                return ResourceManager.GetString("Farm_Jungle_Q_Big", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Jungle clear Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Farm_Jungle_Str {
            get {
                return ResourceManager.GetString("Farm_Jungle_Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ E ] Use - [ All type minions ]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Farm_Lane_E_All {
            get {
                return ResourceManager.GetString("Farm_Lane_E_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ E ] Use - [ Siege, Super minions ]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Farm_Lane_E_Big {
            get {
                return ResourceManager.GetString("Farm_Lane_E_Big", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If mana is higher than [ n% ], [ E ] is used 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Farm_Lane_E_Mana {
            get {
                return ResourceManager.GetString("Farm_Lane_E_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of killable Minions &gt;= [ n ], [ E ] is used과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Farm_Lane_E_Num {
            get {
                return ResourceManager.GetString("Farm_Lane_E_Num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ Q ] Use과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Farm_Lane_Q {
            get {
                return ResourceManager.GetString("Farm_Lane_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If mana is higher than [ n% ], [ Q ] is used 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Farm_Lane_Q_Mana {
            get {
                return ResourceManager.GetString("Farm_Lane_Q_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of killable Minions &gt; [ n ], [ Q ] is used과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Farm_Lane_Q_Num {
            get {
                return ResourceManager.GetString("Farm_Lane_Q_Num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lane clear Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Farm_Lane_Str {
            get {
                return ResourceManager.GetString("Farm_Lane_Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language ( 언어 )과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Intro_Language_Select {
            get {
                return ResourceManager.GetString("Intro_Language_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Language -&gt; Press [ F5 ] key과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Intro_Language_Str {
            get {
                return ResourceManager.GetString("Intro_Language_Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ Nebula ] Kalista - 6.16.0.0과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Intro_Str_0 {
            get {
                return ResourceManager.GetString("Intro_Str_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you like this addon, hope Upvote click or donation.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Intro_Str_1 {
            get {
                return ResourceManager.GetString("Intro_Str_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Donated amount will be used for the development of better addon. Thank you.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Intro_Str_2 {
            get {
                return ResourceManager.GetString("Intro_Str_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blade of the Ruined King과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_A_Blade {
            get {
                return ResourceManager.GetString("Item_A_Blade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If player hp is lower than [ n% ], [ Blade of the Ruined King ] is used과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_A_Blade_Hp {
            get {
                return ResourceManager.GetString("Item_A_Blade_Hp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bilgewater Cutlass과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_A_Blige {
            get {
                return ResourceManager.GetString("Item_A_Blige", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Youmuu&apos;s Ghostblade과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_A_Youmu {
            get {
                return ResourceManager.GetString("Item_A_Youmu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blind과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_Buff_Blind {
            get {
                return ResourceManager.GetString("Item_Buff_Blind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Charm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_Buff_Charm {
            get {
                return ResourceManager.GetString("Item_Buff_Charm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fear과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_Buff_Fear {
            get {
                return ResourceManager.GetString("Item_Buff_Fear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Knockup과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_Buff_Knockup {
            get {
                return ResourceManager.GetString("Item_Buff_Knockup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Polymorph과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_Buff_Ploymorph {
            get {
                return ResourceManager.GetString("Item_Buff_Ploymorph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Poisons과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_Buff_Poisons {
            get {
                return ResourceManager.GetString("Item_Buff_Poisons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Silence과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_Buff_Silence {
            get {
                return ResourceManager.GetString("Item_Buff_Silence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Slow과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_Buff_Slow {
            get {
                return ResourceManager.GetString("Item_Buff_Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stun과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_Buff_Stun {
            get {
                return ResourceManager.GetString("Item_Buff_Stun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Supression과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_Buff_Supression {
            get {
                return ResourceManager.GetString("Item_Buff_Supression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Taunt과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_Buff_Taunt {
            get {
                return ResourceManager.GetString("Item_Buff_Taunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quicksilver Sash, Mercurial Scimitar cast speed - [ /ms ]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_D_CastDelay {
            get {
                return ResourceManager.GetString("Item_D_CastDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mercurial Scimitar과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_D_Mercurial {
            get {
                return ResourceManager.GetString("Item_D_Mercurial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quicksilver Sash과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_D_QuickSilver {
            get {
                return ResourceManager.GetString("Item_D_QuickSilver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select to remove the buff과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_D_Str {
            get {
                return ResourceManager.GetString("Item_D_Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※ Only!! It works in combo mode.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item_Srt {
            get {
                return ResourceManager.GetString("Item_Srt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ E ] Use과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Combo_E {
            get {
                return ResourceManager.GetString("Main_Combo_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If mana is higher than [ n% ], [ E ] is used 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Combo_E_Mana {
            get {
                return ResourceManager.GetString("Main_Combo_E_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ Q ] Use과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Combo_Q {
            get {
                return ResourceManager.GetString("Main_Combo_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If mana is higher than [ n% ], [ Q ] is used과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Combo_Q_Mana {
            get {
                return ResourceManager.GetString("Main_Combo_Q_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Combo Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Combo_Str {
            get {
                return ResourceManager.GetString("Main_Combo_Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ W ] Passive used과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Combo_W {
            get {
                return ResourceManager.GetString("Main_Combo_W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ Q ] Style과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Como_QStyle {
            get {
                return ResourceManager.GetString("Main_Como_QStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   First [ Q ]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Como_QStyle0 {
            get {
                return ResourceManager.GetString("Main_Como_QStyle0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AA ⇒ [ Q ] ⇒ [ E ]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Como_QStyle1 {
            get {
                return ResourceManager.GetString("Main_Como_QStyle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ E ] Use과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Harass_E {
            get {
                return ResourceManager.GetString("Main_Harass_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If mana is higher than [ n% ], [ E ] is used 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Harass_E_Mana {
            get {
                return ResourceManager.GetString("Main_Harass_E_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ E ] Stack count과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Harass_E_Stack {
            get {
                return ResourceManager.GetString("Main_Harass_E_Stack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ Q ] Use과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Harass_Q {
            get {
                return ResourceManager.GetString("Main_Harass_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If mana is higher than [ n% ], [ Q ] is used 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Harass_Q_Mana {
            get {
                return ResourceManager.GetString("Main_Harass_Q_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Harass Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Harass_Str {
            get {
                return ResourceManager.GetString("Main_Harass_Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Before death Rend is used과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_E_Death {
            get {
                return ResourceManager.GetString("Misc_E_Death", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If player hp is lower than [ n% ] Rend is used과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_E_Death_Hp {
            get {
                return ResourceManager.GetString("Misc_E_Death_Hp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rend damage adjust과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_E_Dmg {
            get {
                return ResourceManager.GetString("Misc_E_Dmg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rend damage calculation reduce [ n ]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_E_Dmg_Value {
            get {
                return ResourceManager.GetString("Misc_E_Dmg_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kill steal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_E_Steal_H {
            get {
                return ResourceManager.GetString("Misc_E_Steal_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Jungle steal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_E_Steal_J {
            get {
                return ResourceManager.GetString("Misc_E_Steal_J", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ E ] Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_E_Str {
            get {
                return ResourceManager.GetString("Misc_E_Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save partner과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_R_Save {
            get {
                return ResourceManager.GetString("Misc_R_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If partner hp is lower than [ n% ], used과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_R_Save_Hp {
            get {
                return ResourceManager.GetString("Misc_R_Save_Hp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ R ] Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_R_Str {
            get {
                return ResourceManager.GetString("Misc_R_Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skin Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_Skin {
            get {
                return ResourceManager.GetString("Misc_Skin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Off과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_Skin_0 {
            get {
                return ResourceManager.GetString("Misc_Skin_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blood moon Kalista과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_Skin_1 {
            get {
                return ResourceManager.GetString("Misc_Skin_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Championship Kalista과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_Skin_2 {
            get {
                return ResourceManager.GetString("Misc_Skin_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SKT T1 Kalista과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_Skin_3 {
            get {
                return ResourceManager.GetString("Misc_Skin_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skin과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_Skin_Text {
            get {
                return ResourceManager.GetString("Misc_Skin_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wall Jump Use과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Misc_WallJump {
            get {
                return ResourceManager.GetString("Misc_WallJump", resourceCulture);
            }
        }
    }
}
